name: Cypress run

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, reopened]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --force
      - name: Run server and test
        run: npm run cy:run:server
      - name: Create report
        if: success() || failure()
        run: npm run report:all
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: test-report
            path: mochawesome-report/